### ISSUE TITLE
Support template obj as parameter for formatNumber options

### ISSUE THREAD

**Issue by nadavoran** [capriza/jslt#3]
Hi, 
First of all this is a very cool project, and I really like your response time 👍 

I'm trying to format a number as currency (it works), but when I'm trying to pass a template obj it crashes. 

for example if I need my currency to be data related (my.currency) if fails (it look like you take the values from the options as is without compiling them)
$formatNumber: {
	locales: "en-us",
	options: {
	  style: "currency",
	  currency: "{{my.currency}}",
	  minimumFractionDigits: 2,
	  maximumFractionDigits: 2,
	  currencyDisplay: "symbol"
        }
}

**Comment by drorschw** [comment]
Fixed
